// File: server/src/constants/adminActions.ts
// What this code does:
// 1) Declares shared constants used across backend modules.
// 2) Centralizes canonical values to avoid hard-coded strings.
// 3) Keeps API/domain identifiers consistent across layers.
// 4) Reduces drift between validation, services, and responses.
export const ADMIN_ACTIONS = {
  ADMIN_CREATED: "ADMIN_CREATED",
  ADMIN_UPDATED: "ADMIN_UPDATED",
  ADMIN_DEACTIVATED: "ADMIN_DEACTIVATED",
  ADMIN_ACTIVATED: "ADMIN_ACTIVATED",

  COHORT_FORM_ASSIGNED: "COHORT_FORM_ASSIGNED",
  FORM_UPDATED: "FORM_UPDATED",
  FORM_FIELDS_UPDATED: "FORM_FIELDS_UPDATED",

  APPLICATION_STAGE_CHANGED: "APPLICATION_STAGE_CHANGED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  APPLICATION_DECISION_SET: "APPLICATION_DECISION_SET",
  PARTICIPATION_CONFIRMED: "PARTICIPATION_CONFIRMED",
  USER_CREATED_FROM_APPLICATION: "USER_CREATED_FROM_APPLICATION",
  APPLICATION_MESSAGE_DRAFT_CREATED: "APPLICATION_MESSAGE_DRAFT_CREATED",
  APPLICATION_MESSAGE_SENT: "APPLICATION_MESSAGE_SENT",
  GENERAL_APPLY_SUBMITTED: "GENERAL_APPLY_SUBMITTED",
  INTERVIEW_CONFIRMED_BY_APPLICANT: "INTERVIEW_CONFIRMED_BY_APPLICANT",
  INTERVIEW_RESCHEDULE_REQUESTED: "INTERVIEW_RESCHEDULE_REQUESTED",
  MESSAGE_TEMPLATE_CREATED: "MESSAGE_TEMPLATE_CREATED",
  MESSAGE_TEMPLATE_UPDATED: "MESSAGE_TEMPLATE_UPDATED",

  INSTRUCTOR_PROFILE_CREATED: "INSTRUCTOR_PROFILE_CREATED",
  INSTRUCTOR_PROFILE_ACTIVATED: "INSTRUCTOR_PROFILE_ACTIVATED",
  INSTRUCTOR_PROFILE_DEACTIVATED: "INSTRUCTOR_PROFILE_DEACTIVATED",
} as const;

export type AdminActionCode = (typeof ADMIN_ACTIONS)[keyof typeof ADMIN_ACTIONS];
